# -*- coding: utf-8 -*-
"""Data_Analysis_of_Student_Mental_Health_DB.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1htGD7eg2xHVKArR5IJPV_ww9BGi0MDmI
"""

#importing Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv('Student Mental health.csv')

df

df.head()

df.shape

df.info()

df.describe()

#Finding out the column number whose age is unknown to us

df["Age"][df["Age"].isna() == True]

# Find Age group from 40 to 45 years

df.loc[40:45]

#Counting Courses which are opted by most of the student

course_count = df["What is your course?"].value_counts().head()
course_count

#Counting number of Female and Male

count_gender = df["Choose your gender"].value_counts()
count_gender

#Finding Mean Age of Female and Male

f_meanage = df["Age"][df["Choose your gender"] == "Female"].mean()

m_meanage = df["Age"][df["Choose your gender"] == "Male"].mean()

print("Mean Age of Female Students:", f_meanage)
print("Mean Age of Male Students:", m_meanage)

#Finding Number of Students who are married and not married respectively

marrital_status = df["Marital status"].value_counts()
marrital_status

#Percentage of students facing depression

depression = df[df["Do you have Depression?"] == "Yes"]["Choose your gender"].count()
depr_perc = depression / len(df["Do you have Depression?"]) * 100
print(depr_perc)

#Percentage of students facing anxiety

anxiety = df[df["Do you have Anxiety?"] == "Yes"]["Choose your gender"].count()
anx_perc = anxiety / len(df["Do you have Anxiety?"]) * 100
print(anx_perc)

#percentage of student having panic attacks

panic_attacks = df[df["Do you have Panic attack?"] == "Yes"]["Choose your gender"].count()
panic_perc = panic_attacks / len(df["Do you have Panic attack?"]) * 100
print(panic_perc)

df['Do you have Depression?'].value_counts().plot(kind='bar')

df['Choose your gender'].value_counts().plot(kind='bar')